### ISSUE TITLE
Resolve node security advisory for acorn

### ISSUE THREAD

**Issue by jsevedge** [MatAtBread/nodent-compiler#8]
The following node security advisory requires acorn 6.4.1+ or 7.1.1+ - https://nodesecurity.io/advisories/1488 

Is that a feasible change to make for this project?  Upstream dependencies are failing an npm audit check.

Revving nodent-compiler version in nodent package would also be great.

**Comment by matAtWork** [comment]
Bumped to acorn v5.7.4, which allegedly fixes the same issue. Sadly acorn v6+ is incompatible with nodent as the plugin API has changed.
